# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: https://github.com/lovejing0306/lovejing0306.github.io
#url: http://github.com/lihuimintu/lihuimintu.github.io
date_format: "ordinal"
title: 莫小苝
subtitle: "Simple maybe, but not easy"
description: "Simple maybe, but not easy"
keywords: Algorithm,Deep Learning,Computer Vision
timezone: Asia/Beijing
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: 莫小苝
#organization: UESTC
#organization_url: http://organization_url.githbu.io
github_username: lovejing0306
location: Beijing
email: lovejing0306@gmail.com

# ---------------- #
#    Components    #
# ---------------- #
components:
    # 文章字数统计
    word_count:
        enabled: true

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home


  -
    href: /categories/
    label: Blog
   
  - href: /archives/
    label: Archive

  -
    href: /open-source/
    label: Open-source
   

  -
    href: /wiki/
    label: Wiki

  -
    href: /links/
    label: Link

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: lovejing0306/lovejing0306.github.io

# ---------------- # 
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
#comments_provider: gitalk
comments_provider: gitalk


# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: wenjun d

    
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: lovejing0306
    repo: lovejing0306.github.io
    oauth:
        client_id: 2099ede60a4e9fcf1a9b
        client_secret: 9cc2ee09ee4a85b2781480ddb339b0f9354b84b4
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: lovejing0306
    repo: lovejing0306.github.io
    clientID: bc95f47af2879cfa56ef
    clientSecret: 76f5e7739eb6616de2fcc91d2fc3c4cdcfeed298
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: G-1XQ1ZH3KDF

# ---------------- #
#    Counter     #
# ---------------- #
# 使用的是learncloud，appid和key更换成自己的
# 先关闭
leancloud:
  enable: false
  app_id: EfLTUbK2fJ0dYLAq609NQ2k4-gzGzoHsz
  app_key: 5Agxeshbunhh9y6XQftwEvGj
